#!/bin/sh

set -eu
set -x

script_dir="$(dirname "$(readlink -f "$0")")"
git_base="$(git -C "$script_dir" rev-parse --show-toplevel)/.git"
hooks_dir="$git_base/hooks"
ln -s ../../scripts/pre-commit "$hooks_dir/pre-commit"
