#!/bin/sh
#
# Pre-commit hook to verify commit correctness.
#

stdout="$(git diff --cached --diff-filter=ACMRTUXB | flake8)"
ret=$?
if [ $ret != 0 ]; then
    echo "flake8 checking failed:"
    cat << EOF
$stdout
EOF
fi
exit $ret
