#!/bin/sh
#
# This script publishes to PyPi.
#

script_dir="$(dirname "$(readlink -e "$0")")"
src_root="$(readlink -e "$script_dir/..")"

set -x
cd "$src_root"
git clean -fdx
scripts/flake8
python3 setup.py sdist bdist_wheel
twine upload dist/*
git clean -fdx
